### ISSUE TITLE
ContextualProperty returns bound method call instead of property

### ISSUE THREAD

**Issue by mshriver** [RonnyPfannschmidt/Sentaku#12]
When a class attribute, `klass.exists` for example, is defined as a ContextualProperty and implemented with an external_getter_implemented_for() decorator, a bound method is returned.

If the method that is decorated with external_getter is also decorated as a property (as one would expect for a ConditionalProperty type), this results in a TypeError as such:

TypeError: 'bool' object is not callable

ContextualProperty.__get__ should not return a bound method, but a property value.

**Comment by RonnyPfannschmidt** [comment]
@mshriver i invited you and some others to push perm, as im not sure i can take a look in the next 2 weeks, please tel me when i missed someone

**Comment by RonnyPfannschmidt** [comment]
closed as misunderstanding - see the related pr
